/*
 * DriveDistanceSubsytem.cpp
 *
 *  Created on: Jan 30, 2015
 *      Author: Ligerbots
 */



// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "DriveDistanceSubsystem.h"

#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

DriveDistanceSubsystem::DriveDistanceSubsystem() : Subsystem("DriveDistanceSubsystem") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	printf("Drive subsystem constructor called.\n");

#ifdef nothing
	lFront = RobotMap::driveFrontLeft;
	lBack = RobotMap::driveBackLeft;
	rFront = RobotMap::driveFrontRight;
	rBack = RobotMap::driveBackRight;
	robotDrive = RobotMap::robotDrive;
#endif

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void DriveDistanceSubsystem::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	printf("Drive subsystem InitDefaultCommand.\n");

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void DriveDistanceSubsystem::DriveDistance() {
	// Set the default command for a subsystem here.
	/*
	int distance = 50000;
	lFront->Set(0.5);
	lBack->Set(0.5);
	while (((CANTalon *)lFront)->GetEncPosition() < distance)  {

	}
	lFront->Set(0.0);
	lBack->Set(0.0);
	*/
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

