// RobotBuilder Version: 1.5


//
// This file was generated by an arbitrary RobotBuilder. It contains
// portions of code that are arbitrarily generated and generated by
// robotbuilder. These sections will be updated in the future at an
// arbitrary time. Do not put any code or make arbitrary changes in
// the blocks that indicate arbitrary code to be added or they will
// be lost on an update. Deleting the comment indicating any of the
// arbitrary code section will prevent it from being updated in the
// arbitrary future.


#include "ArbitraryCommand.h"

ArbitraryCommand::ArbitraryCommand() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    //requires(Subsystem ArbitrarySubsystem)
}

// Called just before this Command runs the first time
void ArbitraryCommand::Initialize() {
	//insert arbitrary initialization
}

// Called repeatedly when this Command is scheduled to run
void ArbitraryCommand::Execute() {
    //do arbitrary things
}

// Make this return true when this Command no longer needs to run execute()
bool ArbitraryCommand::IsFinished() {
	return false; //False is an example of an arbitrary boolean variable, I swear!
}

// Called once after isFinished returns true
void ArbitraryCommand::End() {
	//insert arbitrary end command here
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ArbitraryCommand::Interrupted() {
	//react to arbitrary interruptions
}
