/*
 * Turn90Command.h
 *
 *  Created on: Jan 29, 2015
 *      Author: Ligerbots
 */

#pragma once





 /* SRC_COMMANDS_DRIVEDISTANCECOMMAND_H_ */
// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#pragma once


#include "Commands/Subsystem.h"
#include "../Robot.h"
#include "DriveCommand.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class AutoTurn90Command: public Command {
private:
	int target;
	float prevLeftEnc,prevRightEnc;

	float distanceTraveledL;

	float distanceTraveledR;
	float leftMotorOutput;
	float rightMotorOutput;
public:
	AutoTurn90Command(int targ);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};
