// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousCommand.h"

AutonomousCommand::AutonomousCommand() {

	AddSequential(new AutoDriveDistanceCommand(1000));
	printf ("Drove forward, about to turn/n");
	AddSequential(new AutoTurn90Command(750));
	printf ("Turned, about to drive/n");
	AddSequential(new AutoDriveDistanceCommand(1000));
	printf ("Autonomous finished/n");
}
