/*
 * DriveDistanceCommand.cpp
 *
 *  Created on: Jan 29, 2015
 *      Author: Ligerbots
 */


// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveDistanceCommand.h"

#include "../Constants.h"


DriveDistanceCommand::DriveDistanceCommand(int dist) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	Requires(Robot::driveSubsystem);
	distance = dist;
	driveCommand = (DriveCommand *)Robot::driveCommand;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void DriveDistanceCommand::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void DriveDistanceCommand::Execute() {
	float leftEnc1 = Robot::driveSubsystem->GetLeftEncoderPosition();
	float rightEnc1 = Robot::driveSubsystem->GetRightEncoderPosition();
	float leftEnc2 = leftEnc1;
	float rightEnc2 = rightEnc1;
	float distanceTraveled = 0.0;

	while (distanceTraveled < distance) {
		bool isDistSensorOK = RobotMap::distanceSensor->GetVoltage() <= distanceSensorThreshold;
		if (!isDistSensorOK) break;
		leftEnc1 = leftEnc2;
		rightEnc1 = rightEnc2;

		if ((distance - distanceTraveled) > 512) {
			Robot::driveSubsystem->robotDrive->ArcadeDrive(-0.8, 0.0);
			printf("High \n");
		}
		/*else if (distanceTraveled < 0.8 * distance){
			Robot::driveSubsystem->robotDrive->ArcadeDrive(-0.5, 0.0);
			printf("Medium \n");
		} */
		else {
			Robot::driveSubsystem->robotDrive->ArcadeDrive(-0.4, 0.0);
			printf("Slow \n");
		}

		leftEnc2 = Robot::driveSubsystem->GetLeftEncoderPosition();
		rightEnc2 = Robot::driveSubsystem->GetRightEncoderPosition();

		distanceTraveled += (leftEnc2 - leftEnc1);
		SmartDashboard::PutNumber("Drive Distance", distanceTraveled);

	}
	Robot::driveSubsystem->robotDrive->ArcadeDrive(0, 0, true);

}

// Make this return true when this Command no longer needs to run execute()
bool DriveDistanceCommand::IsFinished() {
	return true;
}

// Called once after isFinished returns true
void DriveDistanceCommand::End() {
	driveCommand->Start();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveDistanceCommand::Interrupted() {

}
