// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVE_H
#define DRIVE_H

#include "../Robot.h"

// This is the voltage from the distanceSensor. As we get closer to an obstacle, the voltage increases
// until we get really close. This should be calibrated so we can read the actual distance, but for
// now we'll just guess at a voltage threshold.


/**
 *
 *
 * @author ExampleAuthor
 */
class DriveCommand: public Command {
public:
	DriveCommand();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};

#endif
