
#pragma once

#include "WPILib.h"


class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	JoystickButton* toggleSolenoidButton;
	Command* toggleSolenoidCommand;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	JoystickButton* reverseSolenoidButton;
	JoystickButton* forwardSolenoidButton;
	//JoystickButton* drivePidButton;
	//JoystickButton* driveCommandButton;

	Command* reverseSolenoidCommand;
	Command* forwardSolenoidCommand;
	//Command* drivePid;
	//Command* driveCommand;

public:
	Joystick* joystick;
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	Joystick* getJoystick();
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

